### ISSUE TITLE
generic connection string

### ISSUE THREAD

**Issue by vitaly-t** [iceddev/pg-connection-string#13]
I have implemented a generic-version [connection-string](https://github.com/vitaly-t/connection-string), which can be used by this library as a special case for PostgreSQL:

* It would support only the first `segment` as property `database`.
* It would support only special values for the `protocol`, such as `postgres` + `socket`

The rest I think would be directly reusable.

**Comment by vitaly-t** [comment]
Version 0.4 has been improved a lot.

**Comment by carnesen** [comment]
@vitaly-t The widely-used package `pg` relies on this one, `pg-connection-string`. I think it would unwise for the author of this package to update the code to use `connection-string`, however robust that library may be, because presumably `pg` users are depending on the specific behavior of the parsing logic here. I suggest closing your issue.

**Comment by vitaly-t** [comment]
@carnesen You should track the issues in the driver related to connection string before calling it unwise.

For one thing, PostgreSQL supports multi-connection strings since version 10, but the driver still doesn't support it, see https://github.com/brianc/node-postgres/issues/1470

For another, the generic connection string is backward compatible, so I don't know on what you based your opinion.

**Comment by hjr3** [comment]
Lots of packages [depdend](https://www.npmjs.com/package/pg-connection-string) on this specific package. Updating the internsl to use [connection-string](https://github.com/vitaly-t/connection-string) would require a major version bump.

Also, node-postgres still depends on [v0.1.3](https://github.com/brianc/node-postgres/blob/master/package.json#L24) of this library.

**Comment by vitaly-t** [comment]
> Lots of packages depdend on this specific package. Updating the internsl to use connection-string would require a major version bump.

`connection-string` is compatible in the way strings are defined. Only the clients that do not follow URL Connection String spec would need an update. So it is not really a big deal.

> Also, node-postgres still depends on v0.1.3 of this library.

In the meantime, everyone is required to include the library independently. And the library's usage is minimal at the moment, only to parse it into an object in [connection-parameters](https://github.com/brianc/node-postgres/blob/0993e4b61ad1bafabc84b0335bc9b4caa8b72847/lib/connection-parameters.js), which is very easy to replace.

**Comment by vitaly-t** [comment]
I would be willing to do a PR for this, if there is any interest.

**Comment by vitaly-t** [comment]
Biting the bullet on this one, [here's the PR that implements it](https://github.com/iceddev/pg-connection-string/pull/32).

**Comment by hjr3** [comment]
> For the lack of the progress either way, to move toward a better generic approach, I no longer want to advocate any kind of integration. For people who want to use connection-string, they can just do so independently, and generate a connection object from it to be passed into the driver, as shown within the Adapters.

https://github.com/iceddev/pg-connection-string/pull/32#issuecomment-538648329
