### ISSUE TITLE
Doesn't respect host in query parameters

### ISSUE THREAD

**Issue by LinusU** [iceddev/pg-connection-string#14]
Currently the following connection string doesn't get parsed properly:

```text
postgresql:///test?host=%2Ftmp%2Fephemeralpg.goZMBg
```

It was generated by the tool [ephemeralpg](http://ephemeralpg.org) and seems to work with other client...

**Comment by tym-oao** [comment]
I was just coming in here to note more or less the same issue. It is not just ephemeralpg; there are many cases for connecting to Postgres via unix domain sockets, and using the `host` parameter is the standard way to do this, according to PostgreSQL docs: https://www.postgresql.org/docs/current/static/libpq-connect.html#LIBPQ-PARAMKEYWORDS

For now, you can work around this using the `socket:` protocol, as described here https://github.com/brianc/node-postgres/pull/487

`socket:` doesn't seem to me to be standard, however, and has other limitations, such as expecting database username and password to match the local unix environment.

I am thinking about a PR to better address `host` querystring support and configuring socket connections in a way that conforms to Postgres documentation. I wanted to see first if there would be enough interest in doing so? Feedback appreciated.

**Comment by vitaly-t** [comment]
b.t.w., the generic [connection-string](https://github.com/vitaly-t/connection-string) parses it fine.

**Comment by vitaly-t** [comment]
[This PR will fix it, if merged](https://github.com/iceddev/pg-connection-string/pull/32).

And if that address represents a socket, then changing it into this:
```
postgresql:///test?socket=%2Ftmp%2Fephemeralpg.goZMBg
```
will result in the host being set correctly:
```json
{host: '/tmp/ephemeralpg.goZMBg'}
```

**Comment by hjr3** [comment]
I believe this has been fixed in https://github.com/iceddev/pg-connection-string/pull/34
