### ISSUE TITLE
Does not escape the # character to %23 when in the password

### ISSUE THREAD

**Issue by NobleUplift** [iceddev/pg-connection-string#23]
I'm trying to connect to a database with the following URL:

```
var client = new pg.Client('postgresql://dwuser:<PASSWORD>@dw:5433/dwdev');
```

`dwuser` is my data warehouse user, and `dw` is a network-defined alias of my data warehouse pointing to its IP. The password, port, and database are self-evident. When I try to use this string, I get the following:

```
Connection failed!  { Error: getaddrinfo ENOTFOUND dwuser dwuser:5432
    at errnoException (dns.js:28:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:73:26)
  code: 'ENOTFOUND',
  errno: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'dwuser',
  host: 'dwuser',
  port: 5432 }
```

It recognizes my username as the hostname and does not accept the custom port.

EDIT: It turns out that my data warehouse has a `#` sign in it. This needs to be escaped to `%23` or manually replaced on my end in order to work

**Comment by hjr3** [comment]
I wrote a quick test to see what was going on:

```js
  it('password contains #', function(){
    var sourceConfig = {
      user:'brian',
      password: 'password#',
      port: 5432,
      host: 'localhost',
      database: 'postgres'
    };
    var connectionString = 'postgres://' + sourceConfig.user + ':' + sourceConfig.password + '@' + sourceConfig.host + ':' + sourceConfig.port + '/' + sourceConfig.database;
    var subject = parse(connectionString);
    console.log(subject);
    subject.password.should.equal(sourceConfig.password);
  });
```

Here is the result:

```js
{
  user: '',
  password: '',
  port: null,
  host: 'brian',
  database: ':password'
}
```

The `#` character is denoting a url fragment.

I am loathe to try and fix this though. I think some of the existing behavior going on is already dangerous. I believe the caller should be wrapping username and password in [encodeURIComponent](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/encodeURIComponent) before constructing the URL.

Example:

```js
encodeURIComponent('password#')
```

**Comment by vitaly-t** [comment]
[This PR will fix it, if merged](https://github.com/iceddev/pg-connection-string/pull/32).

**Comment by hjr3** [comment]
As mentioned earlier, the caller should be wrapping username and password in `encodeURIComponent` before constructing the URL.
