### ISSUE TITLE
Prep v2.1.0 release

### ISSUE THREAD

**Issue by hjr3** [iceddev/pg-connection-string#29]
Changes:

`git shortlog --no-merges v2.0.0...`:

```
Benjie Gillam (1):
      Only publish the required files

Herman J. Radtke III (2):
      Add support for TLS parameters in URI
      ssl=0 is now parses to false

Youngwook Kim (1):
      Add supporting username and password for socket connections

benny-medflyt (1):
      Update Typescript definitions
```

https://github.com/iceddev/pg-connection-string/compare/v2.0.0...master

**Comment by hjr3** [comment]
I think we should solve #19 and then cut a new release.

**Comment by hjr3** [comment]
@monteslu please review these changes and approve a v2.1.0 release to npm.

**Comment by hjr3** [comment]
@benjie @ywkim @benny-medflyt would any of you mind giving this release a review? I want another set of eyes before I promote this. @monteslu seems busy at the moment.

**Comment by abowerman** [comment]
`2.1.0` published, thanks @hjr3

**Comment by hjr3** [comment]
https://github.com/iceddev/pg-connection-string/releases/tag/v2.1.0
