### ISSUE TITLE
connectionString to TLSv1.3 works in python, but here got an error: connection requires a valid client certificate

### ISSUE THREAD

**Issue by segatrade** [iceddev/pg-connection-string#33]
Use this connectionString:

`connectionString = "postgresql://db_user:'pass%w@ord'@11.11.111.111:5555/postgres?ssl=true&sslcert=/home/username/.ssh/client.crt&sslkey=/home/username/.ssh/client.key&sslrootcert=/home/username/.ssh/ca.crt&"`

Got an error:

`error: connection requires a valid client certificate`

Also tried:
`ssl=1` - same error?
`sslmode=verify-full` - just ignore ssl

Same string with `sslmode=verify-full` works perfect in python

Nodejs version: v12.13.1
Ubuntu 18.04 WSL
OpenSSL 1.1.1  11 Sep 2018
PostgreSQL server TLSv1.3

import ssl
ssl.OPENSSL_VERSION
'OpenSSL 1.1.1  11 Sep 2018'

**Comment by hjr3** [comment]
This is the connection string parser. I think your issue is with https://github.com/brianc/node-postgres, which normally runs in pure JavaScript (not libpq bindings). Try installing node-postgres with the libpq bindings and see if that fixes it. If not, please open an issue in that repo.
