### ISSUE TITLE
documentation for URL format

### ISSUE THREAD

**Issue by djmitche** [iceddev/pg-connection-string#35]
Is there documentation of the URL format this library parses?  https://node-postgres.com/features/connecting leads to this repo, but it's sort of a dead-end from there.  In particular, I was looking for how to ensure SSL is used.

If not, would a PR adding some info to the README be helpful?

**Comment by hjr3** [comment]
I think the most accurate documentation is in the form of the behavorial tests: https://github.com/iceddev/pg-connection-string/blob/master/test/parse.js

If you want to see how ssl works, check out these [tests](https://github.com/iceddev/pg-connection-string/blob/master/test/parse.js#L178-L215).

If you want to add to the README, I would accept the PR.
