### ISSUE TITLE
Moving this module into node-postgres monorepo

### ISSUE THREAD

**Issue by hjr3** [iceddev/pg-connection-string#37]
Please see the discussion here: https://github.com/brianc/node-postgres/pull/2105#issuecomment-589179652

If that does happen, then I suggest we archive this repo and point people to node-postgres. Old releases will continue to function and new development will be in lock-step with node-postgres.

**Comment by brianc** [comment]
Hey I'm planning on starting on this today if y'all don't have objections?!  I have a couple things coming up I'd like to include here & putting this in the monorepo would make it easier!

**Comment by brianc** [comment]
PR here! https://github.com/brianc/node-postgres/pull/2184

Gonna ping you on the PR so we can discuss publish access or npm package ownership transfer.

**Comment by hjr3** [comment]
I believe @iceddev or @monteslu would be the ones who can discuss npm permissions.

**Comment by hjr3** [comment]
Now that https://github.com/brianc/node-postgres/pull/2184 has landed, we should direct people to that repo. I believe the best option is to archive this repo and update the README with instructions to visit https://github.com/brianc/node-postgres

@louiemontes let me know what you think

**Comment by brianc** [comment]
Just wanted to thank y'all for your help w/ this.

I'm releasing a new `pg` with the "monorepo" version of `pg-connection-string` today!

https://github.com/brianc/node-postgres/pull/2196

Please don't hesitate to come contribute on the main repo too - you're all always welcome! ❤️

**Comment by sonicdoe** [comment]
Now that https://github.com/iceddev/pg-connection-string/pull/41 is merged, what do you think about [archiving](https://docs.github.com/en/free-pro-team@latest/github/creating-cloning-and-archiving-repositories/archiving-repositories) this repository ([as suggested in the original post](https://github.com/iceddev/pg-connection-string/issues/37#issue-568448434))?
