### ISSUE TITLE
Support for RDS JSON-style connection strings

### ISSUE THREAD

**Issue by stephenh** [iceddev/pg-connection-string#38]
This is perhaps a little too-cute, but for applications/libraries using Amazon's RDS, RDS/CloudFormation can [auto-secret/manage secrets](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-secretsmanager-secrettargetattachment.html) in the AWS Secrets Manager that ends up being a JSON string that looks like:

```
{
  "host":"whateverrds.amazon.com",
  "port":5432,
  "username":"...",
  "password":"...",
  "dbname":"..."
}
```

(Without newlines, just formatted for the issue.)

It'd be nice if I could call `parse(...)` with the ^ string and have it recognize "oh right this is RDS json" and "do the right thing".

My use case is that I'm writing a library that reads connection information from an environment variable, and it'd be great if users could pass either the currently-supported `parse` connection strings, or, if they're running in RDS, this auto-managed secret value value.

Granted, I can manage this sort of "if/else" in my library, dunno, just seemed like it'd be neat (and lazy for me) if pg-connection-string did it.

I can work on a PR if this seems okay.

**Comment by hjr3** [comment]
@stephenh interesting use case. I am not sure what "do the right thing" is though. Also, we just merge this repo into node-postgres in https://github.com/brianc/node-postgres/pull/2184 . That probably means we should take that discussion over to that repository.

**Comment by stephenh** [comment]
Great, saw that that happened. I'll re-post over there.
