### ISSUE TITLE
Parsing library should not whitelist keys

### ISSUE THREAD

**Issue by kevinburkeshyp** [iceddev/pg-connection-string#8]
A Postgres connection can take a number of different configuration arguments: http://www.postgresql.org/docs/9.4/static/libpq-connect.html

Only a handful are parsed and returned by this library; all additional configuration parameters are filtered.

The library should assume that the user knows the configuration string they are trying to pass, and pass through that configuration string.

**Comment by phated** [comment]
I think you are confused what this library is doing.  It turns a string into an object usable by node-postgres.  I don't see how you would "pass through a configuration string".

**Comment by kevinburkeshyp** [comment]
Sorry - as an example, the Go `lib/pq` library lets you pass through runtime configuration as part of the connection string, see https://godoc.org/github.com/lib/pq#hdr-Connection_String_Parameters. These include any of the values here: http://www.postgresql.org/docs/current/static/runtime-config-client.html

As it's currently implemented, I believe all of these values would be stripped from the connection string by this library

**Comment by kevinburkeshyp** [comment]
(there are also changes to node-postgres that would need to get made to make this happen, but I'm trying to figure out the least invasive way to make this change)

**Comment by elmigranto** [comment]
Relevant pg issue: brianc/node-postgres#1095

> It turns a string into an object usable by node-postgres.

Yep, except it drops relevant bits from connection string, like non-whitelisted query string params. So, for example, there is no way to specify time zone.

**Comment by hjr3** [comment]
Should be resolved by https://github.com/iceddev/pg-connection-string/pull/7
